name: Generate QZTV-4 EPG

permissions:
  contents: write   # <-- grant write permission for repo contents

on:
  schedule:
    - cron: '9 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: generator/qztv
        run: npm install

      - name: Generate EPG
        uses: ./generator/qztv
        with:
          channel_group: QZTV
          channel_id: QZTV4
          display_name: QZTV-4
          output_path: parts/qztv4.xml.gz

      - name: Commit output to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull
          git add parts/qztv4.xml.gz
          git diff --cached --quiet || git commit -m "Update QZTV EPG [auto]"
          git push
