name: Generate local EPGs

permissions:
  contents: write   # <-- grant write permission for repo contents

on:
  #schedule:
  #  - cron: '3 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1 # Run one by one to avoid Git push conflicts
      matrix:
        channel:
          - id: CHC1
            name: CHC动作电影
            group: CHC
          - id: CHC2
            name: CHC家庭影院
            group: CHC
          - id: CHC3
            name: CHC影迷电影
            group: CHC
          - id: GZTV1
            name: 广州综合
            group: GZTV
          - id: GZTV2
            name: 广州新闻
            group: GZTV
          - id: GZTV4
            name: 广州影视
            group: GZTV
          - id: GZTV6
            name: 广州法治
            group: GZTV
          - id: GZDSTGGPD
            name: 南国都市
            group: GZTV
          - id: SZTV2
            name: 深圳都市
            group: SZTV
          - id: SZTV3
            name: 深圳电视剧
            group: SZTV
          - id: SZTV7
            name: 深圳少儿
            group: SZTV
          - id: SZTV9
            name: 深圳移动电视
            group: SZTV
          - id: SHHAI1
            name: 上海新闻综合
            group: SHHAI
          - id: SHHAI2
            name: 上海第一财经
            group: SHHAI
          - id: SHHAI5
            name: 五星体育
            group: SHHAI
          - id: SHHAI6
            name: 上海纪实人文
            group: SHHAI
          - id: SHHAI7
            name: 上海都市
            group: SHHAI
          - id: BTV2
            name: 北京文艺
            group: BTV
          - id: BTV4
            name: 北京影视
            group: BTV
          - id: BTV5
            name: 北京财经
            group: BTV
          - id: BTV7
            name: 北京生活
            group: BTV
          - id: BTV9
            name: 北京新闻
            group: BTV
          - id: BTV12
            name: 北京纪实科教
            group: BTV
          #- id: ZJTV2
          #  name: 钱江都市
          #  group: ZJTV
          #- id: ZJTV3
          #  name: 浙江经济生活
          #  group: ZJTV
          #- id: ZJTV4
          #  name: 浙江教科影视
          #  group: ZJTV
          #- id: ZJTV6
          #  name: 浙江民生休闲
          #  group: ZJTV
          #- id: ZJTV7
          #  name: 浙江新闻
          #  group: ZJTV
          #- id: ZJTV8
          #  name: 浙江少儿
          #  group: ZJTV
          
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: generator/qztv
        run: npm install

      - name: Generate EPG
        uses: ./generator/qztv
        with:
          channel_group: ${{ matrix.channel.group }}
          channel_id: ${{ matrix.channel.id }}
          display_name: ${{ matrix.channel.name }}
          output_path: parts/${{ matrix.channel.id }}.xml.gz

      - name: Commit output to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull
          git add parts/${{ matrix.channel.id }}.xml.gz
          git diff --cached --quiet || git commit -m "Update ${{ matrix.channel.id }} EPG [auto]"
          git push
